sudo: required
services:
  - docker

before_install:
  - docker build -t davidkwan/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run davidkwan/react-test npm test -- --coverage # npm run test is watch mode, never exits. coverage forces an exit

after_success:
  - docker build -t davidkwan/multi-container-deployment-client ./client
  - docker build -t davidkwan/multi-container-deployment-nginx ./nginx
  - docker build -t davidkwan/multi-container-deployment-server ./server
  - docker build -t davidkwan/multi-container-deployment-worker ./worker

deploy:
  - provider: script
    script: bash ./scripts/docker_push.sh
    on:
      branch: master
  - provider: elasticbeanstalk
    region: us-east-1
    app: multi-container-deployment
    env: MultiContainerDeployment-env
    bucket_name: elasticbeanstalk-us-east-1-067028029760
    bucket_path: multi-container-deployment
    on:
      branch: master
    access_key_id:
      secure: $AWS_ACCESS_KEY
    secret_access_key:
      secure: $AWS_SECRET_KEY
